import 'package:flutter/material.dart';
import 'package:flutter_osm_interface/flutter_osm_interface.dart';

import '../../widgets/mobile_osm_flutter.dart';

Widget getWidget({
  BaseMapController controller,
  bool trackMyPosition,
  OnGeoPointClicked onGeoPointClicked,
  OnLocationChanged onLocationChanged,
  ValueNotifier<bool> mapIsReadyListener,
  ValueNotifier<Widget> dynamicMarkerWidgetNotifier,
  List<StaticPositionGeoPoint> staticPoints = const [],
  Widget mapIsLoading,
  List<GlobalKey> globalKeys,
  Map<String, GlobalKey> staticIconGlobalKeys,
  MarkerOption markerOption,
  RoadConfiguration roadConfiguration,
  bool showZoomController = false,
  bool showDefaultInfoWindow = false,
  bool isPicker = false,
  bool showContributorBadgeForOSM = false,
  double stepZoom = 1,
  double initZoom = 2,
  double minZoomLevel = 2,
  double maxZoomLevel = 18,
  UserLocationMaker userLocationMarker,
  Function(bool) onMapIsReady,
  bool androidHotReloadSupport = false,
}) =>
    MobileOsmFlutter(
      controller: controller,
      onGeoPointClicked: onGeoPointClicked,
      onLocationChanged: onLocationChanged,
      mapIsReadyListener: mapIsReadyListener,
      mapIsLoading: mapIsLoading,
      staticIconGlobalKeys: staticIconGlobalKeys,
      trackMyPosition: trackMyPosition,
      dynamicMarkerWidgetNotifier: dynamicMarkerWidgetNotifier,
      showZoomController: showZoomController,
      showDefaultInfoWindow: showDefaultInfoWindow,
      showContributorBadgeForOSM: showContributorBadgeForOSM,
      markerOption: markerOption,
      isPicker: isPicker,
      roadConfig: roadConfiguration,
      staticPoints: staticPoints,
      globalKeys: globalKeys,
      onMapIsReady: onMapIsReady,
      userLocationMarker: userLocationMarker,
      initZoom: initZoom,
      minZoomLevel: minZoomLevel,
      maxZoomLevel: maxZoomLevel,
      stepZoom: stepZoom,
      androidHotReloadSupport: androidHotReloadSupport,
    );
